plugins {
	id 'com.android.application'
}

android {
	compileSdk 34
	
	defaultConfig {
		applicationId "com.mt.dex2jar"
		namespace "com.mt.dex2jar"
		minSdkVersion 21
		targetSdkVersion 28
		versionCode 1
		versionName "1.0"
	}
	
	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
		}
	}


	/**
	 * During a release build assemblerelease the Android gradle plugin runs a task called lintVitalAnalyzeRelease to
	 * check your code for issues On newer versions of AGP and Java, this specific lint analysis task can occasionally
	 * fail or crash due to tool compatibility issues
	 * @fix
	 */
	lint {
		checkReleaseBuilds false
		abortOnError false
	}
}

dependencies {
	implementation fileTree(dir: 'libs', include: ['*.jar'])
	implementation 'androidx.appcompat:appcompat:1.6.1'
}
